# consul local net cluster
version: '3'

services:
  # Define consul cluster
  consul1:
    image: gcr.io/etcd-development/etcd:v3.3.11
    network_mode: host
    command:
      - /usr/local/bin/etcd
      - --name=s1
      - --data-dir=/etcd-data 
      - --listen-client-urls=http://localhost:12379 
      - --advertise-client-urls=http://localhost:12379 
      - --listen-peer-urls=http://localhost:12380 
      - --initial-advertise-peer-urls=http://localhost:12380 
      - --initial-cluster 
      - s1=http://localhost:12380,s2=http://localhost:22380,s3=http://localhost:32380 
      - --initial-cluster-token=tkn 
      - --initial-cluster-state=new

  # consul agent
  consul-agent:
    image: gcr.io/etcd-development/etcd:v3.3.11
    network_mode: host
    ports:
      - 2380:2380/tcp
      - 2379:2379/tcp
    command:
      - /usr/local/bin/etcd
      - --proxy=on
      - --listen-client-urls=http://localhost:2379
      - --initial-cluster 
      - s1=http://localhost:12380,s2=http://localhost:22380,s3=http://localhost:32380 

    

  registrator:
    image: gliderlabs/registrator:latest
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: etcd://localhost:2379
