# consul no cluster
version: '3'

services:
  consul:
    image: consul:latest
    container_name: consul
    command: agent -ui
    ports:
      - 8500:8500
      - 8080:80
      - 8443:443
    environment:
      - CONSUL_BIND_INTERFACE=eth0

  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul
    command: consul://consul:8500
