# etcd local net cluster - broken
version: '3'

services:
  etcd:
    image: gcr.io/etcd-development/etcd:v3.3.11
    ports:
      - "4001:4001"
      - "2380:2380"
      - "2379:2379"
    command: "/usr/local/bin/etcd --name=s1 \
      --data-dir=/etcd-data \
      --advertise-client-urls=http://localhost:2379,http://localhost:4001 \
      --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001 \
      --initial-advertise-peer-urls=http://127.0.0.1:2380 \
      --listen-peer-urls=http://0.0.0.0:2380 \
      --initial-cluster=s1=http://127.0.0.1:2380 \
      --initial-cluster-token=tkn \
      --initial-cluster-state=new"
    

  registrator:
    image: gliderlabs/registrator:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: etcd://etcd:4001
