# etcd docker net cluster. broken as etcd only lets you use ip/localhost for listening
version: '3'

services:
  # Define etcd cluster
  etcd1:
    image: gcr.io/etcd-development/etcd:v3.3.11
    command:
      - /usr/local/bin/etcd
      - --name=s1
      - --data-dir=/etcd-data 
      - --listen-client-urls=http://etcd1:12379 
      - --advertise-client-urls=http://etcd1:12379 
      - --listen-peer-urls=http://etcd1:12380 
      - --initial-advertise-peer-urls=http://etcd1:12380 
      - --initial-cluster 
      - s1=http://etcd1:12380,s2=http://etcd2:22380,s3=http://etcd3:32380 
      - --initial-cluster-token=tkn 
      - --initial-cluster-state=new

  etcd2:
    image: gcr.io/etcd-development/etcd:v3.3.11
    command:
      - /usr/local/bin/etcd
      - --name=s2
      - --data-dir=/etcd-data 
      - --listen-client-urls=http://etcd2:22379 
      - --advertise-client-urls=http://etcd2:22379 
      - --listen-peer-urls=http://etcd2:22380 
      - --initial-advertise-peer-urls=http://etcd2:22380 
      - --initial-cluster 
      - s1=http://etcd1:12380,s2=http://etcd2:22380,s3=http://etcd3:32380 
      - --initial-cluster-token=tkn 
      - --initial-cluster-state=new

  etcd3:
    image: gcr.io/etcd-development/etcd:v3.3.11
    command:
      - /usr/local/bin/etcd
      - --name=s3
      - --data-dir=/etcd-data 
      - --listen-client-urls=http://etcd3:32379 
      - --advertise-client-urls=http://etcd3:32379 
      - --listen-peer-urls=http://etcd3:32380 
      - --initial-advertise-peer-urls=http://etcd3:32380 
      - --initial-cluster 
      - s1=http://etcd1:12380,s2=http://etcd2:22380,s3=http://etcd3:32380 
      - --initial-cluster-token=tkn 
      - --initial-cluster-state=new

  # etcd proxy
  etcd-proxy:
    image: gcr.io/etcd-development/etcd:v3.3.11
    ports:
      - 2380:2380/tcp
      - 2379:2379/tcp
    command:
      - /usr/local/bin/etcd
      - --proxy=on
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster 
      - s1=http://etcd1:12380,s2=http://etcd2:22380,s3=http://etcd3:32380 

    

  registrator:
    image: gliderlabs/registrator:latest
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: etcd://etcd-proxy:2379

  #nginx
  #app
